
export const roles = [
    { name: 'Warga', image: '/icons/icon_ww_warga.svg', side: 'manusia', desc: "Role ini merupakan role dasar tanpa kemampuan khusus. Satu-satunya tugasnya adalah berpartisipasi dalam voting untuk menentukan pemain yang akan dieliminasi pada siang hari." },
    { name: 'Peramal', image: '/icons/icon_ww_peramal.svg', side: 'manusia', desc: "Setiap malam, role ini memiliki kemampuan untuk melihat role pemain lainnya. Tugas utamanya adalah menemukan para Werewolf dan menyampaikan informasi tersebut pada siang hari. Namun, ia harus melakukannya dengan cara yang cermat dan strategis agar identitasnya tetap tersembunyi." },
    { name: 'Penyihir', image: '/icons/icon_ww_penyihir.svg', side: 'manusia', desc: "Setiap malam, role ini memiliki kemampuan untuk memberikan sebuah ramuan kepada pemain lain. Jika ramuan tersebut diberikan kepada seorang Werewolf, maka Werewolf tersebut akan mati. Namun, ramuan ini tidak akan berpengaruh pada manusia, kecuali jika pada malam yang sama manusia tersebut dibunuh oleh Werewolf. Dalam situasi tersebut, jika sang penyihir memberikan ramuannya kepada manusia yang terbunuh, maka manusia itu akan hidup kembali." },
    { name: 'Dukun', image: '/icons/icon_ww_dukun.svg', side: 'manusia', desc: "Pada malam hari, role ini memiliki kemampuan untuk berkomunikasi dengan pemain yang sudah mati. Dengan informasi yang mereka peroleh, role ini dapat membantu mengungkap siapa sebenarnya Werewolf di antara para pemain yang masih hidup." },
    { name: 'Raja', image: '/icons/icon_ww_raja.svg', side: 'manusia', desc: "Setiap 2 hari sekali role ini dapat mengambil hak suara pemain lainnya sehingga role ini dapat memberikan vote sebanyak 2 kali pada hari yang sama." },
    { name: 'Dark Werewolf', image: '/icons/icon_ww_darkwerewolf.svg', side: 'werewolf', desc: "Role ini merupakan antagonis utama dalam permainan. Tugas mereka adalah menyembunyikan identitas asli mereka agar tidak terungkap oleh pemain lainnya. Pada siang hari, mereka dapat berpartisipasi dalam diskusi dan memiliki hak suara seperti pemain lain. Namun, pada malam hari, mereka akan bangun secara diam-diam dan memilih satu manusia untuk dibunuh." },
    { name: 'Werewolf', image: '/icons/icon_ww_werewolf.svg', side: 'werewolf', desc: "Role ini memiliki kesamaan dengan Werewolf pada umumnya, tetapi dengan kemampuan khusus. Satu kali pada malam tertentu, role ini dapat memilih satu manusia untuk diubah menjadi Werewolf, menambah jumlah sekutu mereka dalam permainan." },
    { name: 'Shapeshifter', image: '/icons/icon_ww_shapeshifter.svg', side: 'werewolf', desc: "Role ini memiliki kemampuan untuk berubah menjadi pemain lain yang mereka pilih untuk satu hari, sehingga mereka akan menjalani peran dan tugas pemain tersebut. Mereka juga dapat menggunakan fitur chat dengan identitas pemain tersebut. Namun, kemampuan ini terbatas dan hanya bisa digunakan beberapa kali selama permainan. Role ini tidak dapat berpartisipasi dalam memilih pemain yang akan dibunuh pada malam hari karena peran utamanya adalah membantu Werewolf dalam permainan." },
];