import { Geist, Geist_Mono, Frijole } from "next/font/google";
import "./globals.css";
import "./globaltw.css"

import "@fa/css/all.css"
import "@fa/css/sharp-duotone-solid.css"
import "@fa/css/sharp-regular.css"
import "@fa/css/sharp-light.css"
import "@fa/css/sharp-solid.css"
import "@fa/css/sharp-thin.css"
// import "@fa/css/.css"

import Header from "@/app/Header"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const frijole = Frijole({
  variable: "--font-frijole",
  subsets: ["latin"],
  weight: "400"
});

export const metadata = {
  title: "PANJI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@4/dark.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${frijole.variable} !no-scrollbar antialiased bg-dark-bg text-dark-text max-w-full min-w-full min-h-screen `}
      >
        <Header />
        <main id="maintag" className="mincomp relative top-0 sm:top-[9vh] px-5 !min-h-screen !max-w-full back">
        {children}
        </main> 

      </body>
    </html>
  );
}
