import { NextResponse } from "next/server";
import { validateApikey, invalidApikey } from "@/app/api/util";
// import axios from "axios";

const json = [
    "A.H. Nasution ",
    "A.Wahab Hasbullah",
    "Abdul Muis",
    "Abdu Halim",
    "Abdulrahman Saleh ",
    "Achmad Rifai ",
    "Achmad Subardjo ",
    "Adam Malik ",
    "Adenan Kapau Gani ",
    "Adisucipto",
    "Ageng Tirtayasa ",
    "Agung Hanyokrokusumo ",
    "Agus Salim",
    "Ahmad Dahlan ",
    "Ahmad Yani",
    "Albertus Soegijapranata",
    "Ali Haji",
    "Alimin ",
    "Amir Hamzah ",
    "Andi Djemma",
    "Andi Mapanyuki",
    "Arie Frederik Lasut",
    "Bagindo Azizchan",
    "Basuki Rahmat",
    "Bau Massepe",
    "Bernard Wilhelm Lapiran",
    "Cipto Mangunkusumo",
    "Cut Nyak Dhien",
    "Cut Nyak Meutia",
    "D.I Pandjaitan",
    "Dewi Sartika",
    "Diponegoro",
    "Djatikusumo ",
    "Douwes Dekker",
    "Fakhruddin ",
    "Fatmawati ",
    "FL Tobing ",
    "Frans Kaisiepo",
    "Gatot Mangkupraja ",
    "Gatot Soebroto ",
    "H.O.S. Tjokroaminoto ",
    "Halim Perdanakusuma ",
    "Hamengkubuwana I ",
    "Hamengkubuwana IX",
    "Hamka",
    "Harun Thohir ",
    "Hasan Basry",
    "Hasanuddin",
    "Hasyim Ashari",
    "Hazairin",
    "Herman Johannes ",
    "I Gusti Ketut Jlantik ",
    "I Gusti Ketut Puja ",
    "I Gusti Ngurah Made Agung",
    "I Gusti Ngurah Rai ",
    "I.J. Kasimo H.",
    "Ida Anak Agung Gde Agung",
    "Idham Chalid ",
    "Ilyas Ya'kub ",
    "Imam Bonjol",
    "Iskandar Muda",
    "Ismail Marzuki",
    "Iswahyudi",
    "Iwa Kusumasumantri",
    "Izaak Huru Doko",
    "J.A. Dimara",
    "J. Leimena",
    "Jamin Ginting",
    "John Lie ",
    "Juanda Kartawijaya ",
    "K.S. Tubun ",
    "Katamso D.",
    "Ki Bagus Hadikusumo ",
    "Ki Hadjar Dewantara",
    "Ki Mangunsarkoro ",
    "Kiras Bangun",
    "Kusumah Atmaja ",
    "L. N. Palar",
    "La Maddukelleng ",
    "M.H. Thamrin",
    "M.T. Haryono",
    "Maria Walanda Maramis",
    "Martha Christina Tiahahu",
    "Marthen Indey",
    "Mas Isman",
    "Mas Mansur",
    "Maskun Sumadireja ",
    "Moehammad Jasin",
    "Mohammad Hatta",
    "Natsir",
    "Mohammad Yamin ",
    "Muhammad Mangundiprojo",
    "Mustopo",
    "Muwardi",
    "Nani Wartabone",
    "Nur Ali",
    "Nyai Ahmad Dahlan",
    "Nyi Ageng Serang",
    "Opu Daeng Risadju",
    "Oto Iskandar Dinata",
    "Pangeran Sambernyowo ",
    "Pajongga Daeng Ngalle ",
    "Pakubuwana VI ",
    "Pakubuwana X ",
    "Pangeran Antasari ",
    "Pattimura ",
    "Pierre Tendean",
    "Pong Tiku ",
    "R. A. Kartini ",
    "R. E. Martadinata ",
    "R. Suprapto",
    "Raden Tumenggung Setia Pahlawan",
    "Radin Inten II",
    "Raja Haji Fisabilillah",
    "Rajiman Wedyodiningrat",
    "Ranggong Daeng Romo",
    "Rasuna Said ",
    "Saharjo",
    "Sam Ratulangi ",
    "Samanhudi ",
    "Silas Papare",
    "Sisingamangaraja XII ",
    "S. Parman ",
    "Slamet Riyadi",
    "Sudirman ",
    "Sugiono ",
    "Suharso",
    "Sukarjo Wiryopranoto ",
    "Sukarni ",
    "Sukarno",
    "Sultan Daeng Raja ",
    "Sultan Mahmud Badaruddin II",
    "Sultan Nuku",
    "Sultan Syahrir",
    "Sultan Thaha Syaifuddin ",
    "Supeno",
    "Supomo",
    "Supriyadi",
    "Suroso",
    "Suryo ",
    "Suryopranoto",
    "Sutomo",
    "Sutomo",
    "Sutoyo Siswomiharjo ",
    "Syafrudding Prawiranegara ",
    "Syarif  Kasim II ",
    "T.B. Simatupang ",
    "T.M. Hasan",
    "Tan Malaka ",
    "Teuku Nyak Arief",
    "Teuku Tjik Ditoro ",
    "Teuku Umar ",
    "Tien Suharto",
    "Tirto Adi Suryo ",
    "Tjilik Riwut ",
    "Tuanku Tambusai ",
    "Untung Suropati ",
    "Urip Sumoharjo ",
    "Usman Janatin ",
    "W.R. Supratman ",
    "W.Z. Johannes",
    "Wahid Hasyim ",
    "Wahidin Sudirohusodo",
    "Wolter Monginsidi",
    "Yos Sudarso",
    "Yusuf Al-Makasari ",
    "Zainal Mustafa ",
    "Zainul Arifin"
  ]

export async function GET(req) {
    if (!validateApikey(req)) return invalidApikey();
    try {

        // const response = await axios.get('https://gist.githubusercontent.com/yuristianto/d2b2f75292927f15b633d9f8a3bd4ec6/raw/5bdb0100530fefd4670d987fbbcf23ed183842d4/hero.json');

        // let dta = [];
        // response.data.forEach((data) => {
        //     dta.push(data.nama);
        // });


        return NextResponse.json({
            success: true,
            nama: json[Math.floor(Math.random() * json.length)]
        });

    } catch (error) {
        console.log(error);
        return NextResponse.json(
            { success: false, error: 'Internal Server Error' },
            { status: 500 }
        );
    }
}